precision: 16
accelerator: ddp
profiler: ${debug.profiler}
max_epochs: 150
gpus: -1
num_nodes: 1
sync_batchnorm: ${model.sync_batchnorm}
num_sanity_val_steps: 10
limit_val_batches: 1.0
accumulate_grad_batches: 1
multiple_trainloader_mode: ${data.dataset.multiple_trainloader_mode}